# Generated by Django 4.1 on 2022-09-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega1', '0002_rename_modelo1_clasemodelo1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasemodelo2',
            name='contrasenia',
            field=models.CharField(default='abc', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clasemodelo2',
            name='usuario',
            field=models.CharField(default='abc', max_length=50),
            preserve_default=False,
        ),
    ]
