# Generated by Django 4.1 on 2022-09-07 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppEntrega1', '0003_clasemodelo2_contrasenia_clasemodelo2_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClaseModelo1',
        ),
        migrations.RenameField(
            model_name='clasemodelo3',
            old_name='profesion',
            new_name='texto',
        ),
    ]
